[tools]
uv = "0.8.24"

[settings]
python.uv_venv_auto = true

[task_config]
includes = ["mise-tasks"]

########## Tasks ##########
[tasks.ci]
run = [
    "uv run ruff check",
    "uv run ruff format --check",
    "uv run mypy",
]