[tools]
uv = "0.8.24"

[tasks.sync]
run = "uv sync"

# FIXME: PRを出す前に消す
[tasks.app_sandbox]
depends = ["sync"]
dir = "{{cwd}}/SerialControllerSandbox"
run = '''
if [ '{{flag(name='dev')}}' = 'true' ]; then
    uv run python -X dev main.py
else
    uv run python main.py
fi
'''

[tasks.app_extension]
depends = ["sync"]
dir = "{{cwd}}/SerialController"
run = '''
if [ '{{flag(name='dev')}}' = 'true' ]; then
    uv run python -X dev Window.py
else
    uv run python Window.py
fi
'''

[tasks.lint]
run = "uv run ruff check --fix"

[tasks.lint_fix]
run = "mise run lint --fix"

[tasks.format]
run = "uv run ruff format"

[tasks.typecheck]
run = "uv run mypy"

[tasks.check]
run = [
    "mise run format",
    "mise run lint",
    "mise run typecheck",
]

[tasks.ci]
depends = ["lint", "format", "typecheck"]
