[project]
name = "Poke-Controller-Modified-Extension"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "KawaSwitch" },
    { name = "Moi-poke" },
    { name = "futo030" },
    { name = "carimatics" },
]
requires-python = "==3.12.*"
dependencies = [
    "gitpython>=3.1.45",
    "numpy>=2.3.5",
    "opencv-python>=4.11.0.86",
    "paho-mqtt>=2.1.0",
    "pandas>=2.3.3",
    "pillow>=12.0.0",
    "plyer>=2.1.0",
    "poke-controller",
    "pygame>=2.6.1",
    "pygubu>=0.39",
    "pynput>=1.8.1",
    "pyserial>=3.5",
    "pythonnet>=3.0.5",
    "requests>=2.32.5",
    "scipy>=1.16.3",
    "windows-capture-device-list>=1.1.0",
]

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "ruff>=0.14.5",
]

[tool.uv.sources]
poke-controller = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

[tool.ruff]
include = [
    "packages/**/*.py",
]
exclude = [
    "packages/poke-controller/src/pokecontroller/app/extension/tkinter/core/**/*.py"
]

[tool.mypy]
files = [
    "packages/**/*.py",
]

# bass settings
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
# for third-party libraries
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["pokecontroller.app.extension.tkinter.core.*"]
ignore_errors = true