include = [
    "packages/**/*.py",
    "apps/**/*.py"
]
exclude = [
    "apps/poke-controller-modified-extension/src/pokecontrollermodifiedextension/components/**/*.py",
    "apps/poke-controller-modified-extension/src/pokecontrollermodifiedextension/core/command/commands/**/*.py",
]

[lint]
extend-select = ["I"]

[lint.isort]
case-sensitive = true
combine-as-imports = true