#!/usr/bin/env -S uv run --script
# @formatter:off
#MISE description="Run all checks in parallel for CI(no auto fix)"
#MISE dir="{{cwd}}"
#MISE sources=["pyproject.toml", "ruff.toml", "mypy.ini", "packages/**/*.py", "apps/**/*.py"]
#MISE depends=["lint", "format --check", "typecheck"]
# @formatter:on
