#!/usr/bin/env -S uv run --script
# @formatter:off
#MISE description="Format the codebase"
#MISE dir="{{cwd}}"
#MISE sources=["pyproject.toml", "ruff.toml", "packages/**/*.py", "apps/**/*.py"]
#USAGE flag "--check" help="Check only" default=#false
# @formatter:on

from pathlib import Path
import sys

project_root = Path(__file__).parent.parent
sys.path.append(str(project_root))

from scripts.utils.command import CrossPlatformCommand, get_usage_envs

if __name__ == '__main__':
    # Get the profile and dev flags from the environment
    env: dict[str, str] = get_usage_envs(("check",))

    # Construct the command to run
    check_flag: list[str] = ["--check"] if env["check"] == "true" else []

    # Run the command
    _ = CrossPlatformCommand().run(
        command=["uv", "run", "ruff", "format", *check_flag],
        cwd=project_root,
    )
