#!/usr/bin/env -S uv run --script
# @formatter:off
#MISE description="Setup development environment"
#MISE dir="{{cwd}}"
#MISE sources=["pyproject.toml", "ruff.toml", "mypy.ini", "packages/**/*.py", "apps/**/*.py"]
#MISE depends=["sync"]
# @formatter:on

from pathlib import Path
import sys

project_root = Path(__file__).parent.parent
sys.path.append(str(project_root))

from scripts.utils.command import CrossPlatformCommand, get_usage_envs

if __name__ == '__main__':
    # Run the command
    _ = CrossPlatformCommand().run(
        command=["git", "config", "core.hooksPath", ".githooks"],
        cwd=project_root,
    )
