#!/usr/bin/env -S uv run --script
# @formatter:off
#MISE description="Typecheck the codebase"
#MISE dir="{{cwd}}"
#MISE sources=["pyproject.toml", "mypy.ini", "packages/**/*.py", "apps/**/*.py"]
# @formatter:on

from pathlib import Path
import sys

project_root = Path(__file__).parent.parent
sys.path.append(str(project_root))

from scripts.utils.command import CrossPlatformCommand

if __name__ == '__main__':
    # Run the command
    _ = CrossPlatformCommand().run(
        command=["uv", "run", "mypy"],
        cwd=project_root,
    )
